name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install mkdocs
        run: poetry install
      - name: Install mkdocs
        run: poetry run pip install -r docs/requirements.txt
      - name: Publish docs
        run: poetry run mkdocs gh-deploy
